"""empty message

Revision ID: 8815906eedfe
Revises: baab742c8bef
Create Date: 2018-09-02 20:46:19.938000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8815906eedfe'
down_revision = 'baab742c8bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'adaptation_node', 'taxonomy', ['TaxonomyID'], ['TaxonomyID'])
    op.create_foreign_key(None, 'taxonomy', 'adaptation_node', ['AdaptationNodeID'], ['AdaptationNodeID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taxonomy', type_='foreignkey')
    op.drop_constraint(None, 'adaptation_node', type_='foreignkey')
    # ### end Alembic commands ###
